# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_value', models.IntegerField()),
                ('item_detail', models.CharField(max_length=255, null=True)),
                ('image_URL', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_made', models.BooleanField(default=False)),
                ('item_giving', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_giving', to='server.Item')),
                ('item_wanted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_wanted', to='server.Item')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('username', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='matched_items',
            field=models.ManyToManyField(through='server.ItemRelationship', to='server.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='server.User'),
        ),
        migrations.AddField(
            model_name='item',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, to='server.User'),
        ),
        migrations.AlterUniqueTogether(
            name='itemrelationship',
            unique_together=set([('item_wanted', 'item_giving')]),
        ),
    ]
